In [1]:
import numpy as np

In [3]:
#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 2, 5], [5, 26,3]])
X

array([[25,  2,  5],
       [ 5, 26,  3]])

In [4]:
#tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [5]:
X.size

6

In [7]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
X [:,0]

array([25,  5])

In [9]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([ 5, 26,  3])

2. ulangi soal nomor 1 menggunakan pytorch

In [10]:
import torch

In [13]:
#buat matrix X berukuran 2x3 menggunakan numpy
X_pt = torch.tensor([[25, 2, 5],[5, 26, 3]])
X_pt

tensor([[25,  2,  5],
        [ 5, 26,  3]])

In [14]:
#tampilkan ukuran dari matrix X
X_pt.shape

torch.Size([2, 3])

In [27]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
X_pt[:,0]

tensor([25,  5])

In [28]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X_pt[1,:]

tensor([ 5, 26,  3])

ulangi soal nomor 1 menggunakan tensorflow

In [19]:
import tensorflow as tf

In [20]:
#buat matrix X berukuran 2x3 menggunakan numpy
X_tf = tf.Variable([[25, 2,5], [5, 26,3]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25,  2,  5],
       [ 5, 26,  3]], dtype=int32)>

In [21]:
#tampilkan ukuran dari matrix X
X_tf.shape

TensorShape([2, 3])

In [24]:
#tampilkan ukuran dari matrix X
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [25]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
X_tf [:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([25,  5], dtype=int32)>

In [29]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
X_tf [1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 26,  3], dtype=int32)>