1. Buat Vector x ukuran 3x1

In [1]:
import numpy as np

In [2]:
#buat vector x dengan ukuran 3x1
x = np.array([30, 3, 0 ]) # type argument is optional, e.g.: dtype=np.float16
x

array([30,  3,  0])

In [3]:
#hitung panjang vector x
len(x)

3

In [4]:
#tampilkan ukuran vector x
x.shape

(3,)

In [5]:
#tampilkan tipe data dari vector x
type (x)

numpy.ndarray

In [6]:
#akses elemen pertama dari vector x
x[0]

np.int64(30)

In [8]:
#tampilkan tipe data elemen pertama dari vector x
type (x[0])

numpy.int64

2.  lakukan transpose pada vector x dan simpan pada variabel x_t

In [9]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([30,  3,  0])

In [10]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [16]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [17]:
y.shape

(1, 3)

In [18]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [19]:
y_t.shape

(3, 1)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

lakukan transpose pada vector x dan simpan pada variabel x_t

In [20]:
import torch
import tensorflow as tf


In [21]:
x_pt = torch.tensor([20, 2, 0])
x_pt

tensor([20,  2,  0])

In [41]:
#Transpose x_pt dan simpan ke variabel x_t
x_t_pt = x_pt.T
x_t_pt

tensor([20,  2,  0])

In [31]:
#tampilkan ukuran vector x_t
x_t_pt.shape

torch.Size([3])

lakukan transpose pada vector y dan simpan pada variabel y_t

In [35]:
y_pt = torch.tensor([1, 2, 3])
y_pt

tensor([1, 2, 3])

In [42]:
#Transpose y_pt dan simpan ke variabel y_t
y_t_pt = y_pt.T
y_t_pt

tensor([1, 2, 3])

In [40]:
#tampilkan ukuran vector y_t
y_t_pt.shape

torch.Size([3])

In [43]:
x_tf = tf.Variable([3, 2, 1])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([3, 2, 1], dtype=int32)>

In [48]:
# Transpose menggunakan tf.transpose
x_tf_t = tf.transpose(x_tf)
print("Transpose TensorFlow shape:", x_tf_t.shape)

Transpose TensorFlow shape: (3,)
